### ISSUE TITLE
Catch monero-wallet-rpc not running

### ISSUE THREAD

**Issue by sneurlax** [sneurlax/monerophp#1]
```

Fatal error: Uncaught RuntimeException: Unable to connect to http://127.0.0.1:28081/json_rpc Error: Failed to connect to 127.0.0.1 port 28081: Connection refused in /home/r/github/monerophp/src/jsonRPCClient.php:155 Stack trace: #0 /home/r/github/monerophp/src/jsonRPCClient.php(98): jsonRPCClient->getResponse('{"jsonrpc":"2.0...') #1 /home/r/github/monerophp/src/daemonRPC.php(80): jsonRPCClient->_run('getblockcount', NULL) #2 /home/r/github/monerophp/src/daemonRPC.php(94): daemonRPC->_run('getblockcount') #3 /home/r/github/monerophp/example.php(11): daemonRPC->getblockcount() #4 {main} thrown in /home/r/github/monerophp/src/jsonRPCClient.php on line 155

```

Error encountered when `monero-wallet-rpc` not running prior to connection

**Comment by sneurlax** [comment]
We don't really need to catch this, it would just be nice for it to be non-fatal.  But maybe it should be for users' safety.
